spring:
  application:
    name: IoT-service
dubbo:
  application:
    name: IoT-service
  protocol:
    port: 20881
  registry:
    address: nacos://40.81.229.5:8848
    username: nacos
    password: nacos

influx:
  token: tUV9DI3xq-9dKMtH1mufyJ_gVIILoPNbWPa345mie-GBoyDMqa7C_8fmce8sI1BwrbOllCYyt_rJlOEvCCk5-Q==

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 18016

