spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

mock:
  api:
    min-delay-ms: ${MOCK_API_MIN_DELAY_MS:500}
    max-delay-ms: ${MOCK_API_MAX_DELAY_MS:1200}
