spring:
  application:
    name: water-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 40.81.229.5:8848
      config:
        name: nacos
        password: nacos
    gateway:
      routes:
        - id: device
          uri: lb://iot-device
          predicates:
            - Path=/device/**,/simulator/**
        - id: service
          uri: lb://IoT-service
          predicates:
            - Path=/service/**,/Data/**
        - id: prediction
          uri: lb://prediction-service
          predicates:
            - Path=/prediction/**,/ai/**
        - id: warning
          uri: lb://warning-service
          predicates:
            - Path=/warn/**
        - id: repair
          uri: lb://repair-service
          predicates:
            - Path=/operations/**,/iot-event/**,/user-report/**
        - id: auth
          uri: lb://Auth-service
          predicates:
            - Path=/auth/**,/signup/**,/user/**
  main:
    web-application-type: reactive
logging:
  # 2. 级别改为 INFO 或 ERROR
  level:
    com.ncwu.watergateway: error
    org.springframework.cloud.gateway: error