dubbo:
  application:
    name: warning-service
    qos-port: 22225
  protocol:
    port: 20888
  registry:
    address: nacos://40.81.229.5:8848
    username: nacos
    password: nacos
  provider:
    timeout: 7000  # 提供方超时时间（毫秒）
spring:
  mail:
    host: smtp.qq.com
    port: 465
    fromEmail: 2405313582@qq.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        debug: false  # 开发时可以设为true查看详细日志